version: "3.9"
services:
  backend:
    container_name: backend-rentme-expressjs
    build: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
    restart: always
    env_file: ./backend/.env
  mongo:
    container_name: database-rentme-mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    restart: always
    volumes:
     - ./backend/data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo:27017/


    