version: "3.9"
services:
  frontend:
    container_name: frontend-rentme-react  
    build: .
    ports:
      - 3000:80
      - 1443:443
    volumes: 
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
    restart: always
    env_file: ./.env.production
  backend:
    container_name: backend-rentme-expressjs
    build: ./backend
    ports:
      - 4000:4000
    restart: always
    env_file: ./backend/prod.env
  #   mongo:
  #   container_name: database-rentme-mongo
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: test
  #     MONGO_INITDB_ROOT_PASSWORD: test
  #   restart: always
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: test
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: test
  #     ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo:27017/