version: "3.9"
services:
  frontend:
    container_name: frontend-rentme-react  
    build: .
    ports:
      - 3000:80
      - 1443:443
    volumes: 
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
      - .:/usr/src/app
    restart: always
  backend:
    container_name: backend-rentme-expressjs
    build: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
    restart: always
