version: "3.3"
services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/jenkins_home/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - rentme-networks
  frontend:
    container_name: frontend-rentme-react  
    build: .
    ports:
      - 80:80
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rentme-networks
  backend:
    container_name: backend-rentme-nestjs
    build: ./backend
    ports:
      - 4000:4000
    networks:
      - rentme-networks
networks:
  rentme-networks:
    