version: "3.9"
services:
  frontend:
    container_name: frontend-rentme-react  
    build: .
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/usr/src/app
    # networks:
    #   - rentme-networks
  backend:
    container_name: backend-rentme-nestjs
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/src/app
#     networks:
#       - rentme-networks
# networks:
#   rentme-networks:
