version: "3.9"
services:
  frontend:
    container_name: frontend-rentme-react  
    build: .
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
  backend:
    container_name: backend-rentme-expressjs
    build: ./backend
    ports:
      - 4000:4000
    env_file: ./backend/.env
    restart: always

