version: "3.3"
services:
  frontend:
    container_name: frontend-rentme-react  
    build: .
    ports:
      - 9000:80
      - 443:443
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rentme-networks
  backend:
    container_name: backend-rentme-nestjs
    build: ./backend
    ports:
      - 4000:4000
    networks:
      - rentme-networks
networks:
  rentme-networks:
    