version: "3.9"
services:
  frontend:
    container_name: frontend-rentme-react  
    build: .
    ports:
      - 3000:80
      # - 443:443
    restart: always
    env_file: ./.env.production
  backend:
    container_name: backend-rentme-expressjs
    build: ./backend
    ports:
      - 4000:4000
    env_file: ./backend/prod.env
    restart: always

